language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter
  - pip install coveralls
script:
  - nosetests --with-coverage

after_success: 
  - coveralls
  - codeclimate-test-reporter
cache: pip